algo_name: DQN

seed: 1024

render: False
eval_render: True

dataloader:
  memory_capacity: 10000
  batch_size: 64

  sample_type: "random"

model:
  observation_dim: 2
  action_type: "discrete"
  action_dim: 3
  action_config:
    acceleration: None
    steering: None

  hidden_dim: 128

trainer:
  gamma: 0.98
  epsilon: 1
  epsilon_decay: 0.995
  epsilon_min: 0.01
  lr: 2e-3
  update_every: 10
  episodes: 1000
  minimal_size: 100
